name = "nakai"
version = "0.3.5"
licences = ["MIT"]
description = "A server-side rendering framework for building web apps with Gleam ✨"
repository = { type = "github", user = "nakaibuild", repo = "nakai" }

[dependencies]
gleam_stdlib = "~> 0.23"

[dev-dependencies]
gleeunit = "~> 0.6"
