name = "nakai"
version = "0.4.1"
licences = ["MIT"]
description = "A server-side rendering framework for building web apps with Gleam ✨"
repository = { type = "github", user = "nakaibuild", repo = "nakai" }

[dependencies]
gleam_stdlib = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 0.7"
