name = "nakai"
version = "0.4.2"
licences = ["MIT"]
description = "A server-side rendering framework for building web apps with Gleam ✨"
repository = { type = "github", user = "nakaibuild", repo = "nakai" }

[dependencies]
gleam_stdlib = "~> 0.27"

[dev-dependencies]
gleam_erlang = "~> 0.18"
gleeunit = "~> 0.10"

[documentation]
hidden_modules = ["nakai/render", "nakai/render/*"]
